version: '3.8'
services:
  db:
    image: mysql
    container_name: apiblog-db
    restart: always
    environment:
      MYSQL_DATABASE: 'apiblog'
      MYSQL_PASSWORD: 'root'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306'
    networks:
      - apiblog-network
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=root --execute \"SHOW DATABASES;\""
      interval: 2s
      timeout: 20s
      retries: 10
    volumes:
      - ./data:/docker-entrypoint-initdb.d
  application:
    container_name: apiblog-application
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - apiblog-network
    depends_on:
      - "db"
networks:
  apiblog-network:
    name: apiblog-network
    driver: bridge
